language: python

env:
  global:
    LINTLY_API_KEY = ${GITHUB_TOKEN} 


jobs:
  include:
    - stage: lint 
      install: 
        pip install flake8
        pip install lintly
      script: flake8 . --exit-zero --ignore=W191,E265 | lintly --format=flake8 --exit-zero
    - stage: deploy
      install:
        - pip install -r requirements/requirements.txt
        - pip install flake8 #delete this after we have scripts
      script:
        - flake8 . --exit-zero  # literally just dummy stuff just to have a script
stages:
  - lint
  - deploy

#deploy:
#  provider: pages
#  skip_cleanup: true
#  github_token: ${GITHUB_TOKEN}  # Set in the settings page of your repository, as a secure variable
#  keep_history: true
#  on:
#    branch: master